export const POST_ACTION_TYPES = {
    FETCH_POST_START: 'FETCH_POST_START',
    FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
    FETCH_POST_FAILURE: 'FETCH_POST_FAILURE',
    ADD_NEW_POST: 'ADD_NEW_POST',
    REMOVE_POST: 'REMOVE_POST',
    SET_CURRENT_POST: 'SET_CURRENT_POST'
}