export const CONVERSATION_ACTION_TYPES = {
    FETCH_CONVERSATION_START: 'FETCH_CONVERSATION_START',
    FETCH_CONVERSATION_SUCCESS: 'FETCH_CONVERSATION_SUCCESS',
    FETCH_CONVERSATION_FAILURE: 'FETCH_CONVERSATION_FAILURE',
    SET_CURRENT_CHAT: 'SET_CURRENT_CHAT'
}